#!/usr/bin/python

import argparse
import MySQLdb
import os
import sys

db_host="127.0.0.1"
db_port=3306
db_user="nextcloud"
db_pass=""
db_name="nextcloud"

# Argument parsing
parser = argparse.ArgumentParser()
parser.add_argument("-H", "--host", help="Database host address")
parser.add_argument("-P", "--port", help="Database port")
parser.add_argument("-u", "--user", help="Database user name")
parser.add_argument("-p", "--passwd", help="Database user password")
parser.add_argument("-d", "--database", help="Database name")

if not len(sys.argv) > 1:
  parser.print_help()
  exit(1)
else:
  args = parser.parse_args()

if args.host:
  db_host=args.host

if args.port:
  db_port=args.port

if args.user:
  db_user=args.user

if args.passwd:
  db_pass=args.passwd

if args.database:
  db_name=args.database

db = MySQLdb.connect(host=db_host,
                     port=db_port,
                     user=db_user,
                     passwd=db_pass,
                     db=db_name)

cur = db.cursor()

# Get table with no auto increment primary key
cur.execute("SELECT DISTINCT CONCAT(t.table_schema,'.',t.table_name) as tbl, t.engine, IF(ISNULL(c.constraint_name),'NOPK','') AS nopk, IF(s.index_type = 'FULLTEXT','FULLTEXT','') as ftidx, IF(s.index_type = 'SPATIAL','SPATIAL','') as gisidx FROM information_schema.tables AS t LEFT JOIN information_schema.key_column_usage AS c ON (t.table_schema = c.constraint_schema AND t.table_name = c.table_name AND c.constraint_name = 'PRIMARY') LEFT JOIN information_schema.statistics AS s ON (t.table_schema = s.table_schema AND t.table_name = s.table_name AND s.index_type IN ('FULLTEXT','SPATIAL'))   WHERE t.table_schema = '" + db_name + "' AND t.table_type = 'BASE TABLE' AND (t.engine <> 'InnoDB' OR c.constraint_name IS NULL OR s.index_type IN ('FULLTEXT','SPATIAL')) ORDER BY t.table_schema,t.table_name;")

# Loop on table with no auto increment primary key 
for row in cur.fetchall():
    # Add PRIMARY KEY AUTO_INCREMENT on table
    cur.execute("ALTER TABLE " + row[0] + " ADD COLUMN `id` INT PRIMARY KEY AUTO_INCREMENT;")

db.close()
