#!/bin/bash

export LANG="en_US.UTF-8"

syntax() {
	echo "Usage: $0 <domain_xml>"
	exit 1
}

DOMAIN_XML=$1

if [ -z "$DOMAIN_XML" ]; then
  # if no xml, print syntax
	syntax
fi;


BACKUP_DIR=`dirname $DOMAIN_XML`
DOMAIN=`basename $DOMAIN_XML .xml`

# Check if VM is running
virsh list | grep -q $DOMAIN && virsh dominfo $DOMAIN | grep -e ^State | grep running

# IF VM is running stop script
if [ $? -eq 0 ]; then
  echo "Please stop VM $DOMAIN first"
  exit 1
fi

# Define domain
virsh define $DOMAIN_XML

# fin all disks but cdrom
DISKS=`virsh domblklist "$DOMAIN" --details | grep -v hdc | grep ^file | awk '{print $4}'`

for d in $DISKS; do
    echo "Restore disk $d"
    cp $BACKUP_DIR/$(basename $d) $d
done
echo "VM: $DOMAIN restored"

# Set Autostart
virsh autostart $DOMAIN

exit 0
