#!/usr/bin/env bash
nodeid=$(curl -m 3 -s http://localhost:9200/_nodes/_local | jq --raw-output '.nodes|keys[]')
masternode=$(curl -m 3 -s http://localhost:9200/_cluster/state/master_node | jq --raw-output '.master_node')
if [[ $nodeid == $masternode ]]; then
      echo "[es:master]"
else      
      echo "[es:slave]"
fi


