#!/bin/bash

ip=$1

syntax() {
    echo: "$0 "
}

firewall-cmd --permanent --zone=public --add-rich-rule="
  rule family=ipv4
  source address=$ip/32
  port protocol=tcp port=9200 accept"


firewall-cmd --permanent --zone=public --add-rich-rule="
  rule family=ipv4
  source address=$ip/32
  port protocol=tcp port=9300 accept"

firewall-cmd --reload
